export const images = [
	{
		src: 'https://source.unsplash.com/random/1240x874/?code',
		original: 'https://source.unsplash.com/random/1240x874/?code',
		width: 1240,
		height: '100%',
		title: 'some content',
	},
	{
		src: 'https://source.unsplash.com/random/1240x875/?dublin',
		original: 'https://source.unsplash.com/random/1240x875/?dublin',
		width: 480,
		height: 240,
		title: "...you wouldn't get this from any other guy...",
	},
	{
		src: 'https://source.unsplash.com/random/1240x877/?code',
		original: 'https://source.unsplash.com/random/1240x877/?code',
		width: 350,
		height: 212,
		title: "...a full commitment's what I'm thinking of...",
	},
	{
		src: 'https://source.unsplash.com/random/1240x875/?amsterdam',
		original: 'https://source.unsplash.com/random/1240x875/?amsterdam',
		width: 480,
		height: 240,
		title: "...you wouldn't get this from any other guy...",
	},
	{
		src: 'https://source.unsplash.com/random/1240x879/?code',
		original: 'https://source.unsplash.com/random/1240x879/?code',
		width: 480,
		height: 240,
		title: "...you wouldn't get this from any other guy...",
	},
	{
		src: 'https://source.unsplash.com/random/1240x879/?dublin',
		original: 'https://source.unsplash.com/random/1240x879/?dublin',
		width: 480,
		height: 240,
		title: "...you wouldn't get this from any other guy...",
	},
	{
		src: 'https://source.unsplash.com/random/1240x878/?app+development',
		original: 'https://source.unsplash.com/random/1240x878/?app+development',
		width: 480,
		height: 240,
		title: '...gotta make you, understand...',
	},
	{
		src: 'https://source.unsplash.com/random/1240x878/?code',
		original: 'https://source.unsplash.com/random/1240x878/?code',
		width: 480,
		height: 240,
		title: '...never gonna give you up...',
	},
	{
		src: 'https://source.unsplash.com/random/1240x878/?web+development+studio',
		original: 'https://source.unsplash.com/random/1240x878/?web+development+studio',
		width: 480,
		height: 240,
		title: '...never gonna let you down...',
	},
	{
		src: 'https://source.unsplash.com/random/1240x875/?dublin',
		original: 'https://source.unsplash.com/random/1240x875/?dublin',
		width: 480,
		height: 240,
		title: "...you wouldn't get this from any other guy...",
	},
	{
		src: 'https://source.unsplash.com/random/1240x875/?web+development',
		original: 'https://source.unsplash.com/random/1240x875/?web+development',
		width: 480,
		height: 240,
		title: "...you wouldn't get this from any other guy...",
	},
	{
		src: 'https://source.unsplash.com/random/1240x876/?amsterdam',
		original: 'https://source.unsplash.com/random/1240x876/?amsterdam',
		width: 480,
		height: 240,
		title: "...you wouldn't get this from any other guy...",
	},
]

export default images
