/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page;
    users: User;
    media: Media; 
  };
  globals: {};
}
export interface Page {
  id: string;
  title: string;
  richText?: {
    [k: string]: unknown;
  }[];
  slug?: string;
  subtitle?: string;
  onemore?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Blocks {
  content?: Array
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
